In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [8]:
data = pd.read_csv("C:\\Thanusha\\Python\\ML master class\\GPA_data.CSV")

In [9]:
data.head()

ID  Gender  Age Extra_Curricular  Study_Hours  Annual_Income  \
0  8867    Male   22        Societies           10        1318792   
1  1316  Female   24        Societies            9         874657   
2  9443    Male   22        Societies           15        1098331   
3  1829  Female   25               No            9        1680585   
4  1989    Male   26               No            7        1361560   

   Distance_From_Home   GPA  
0                 154  1.76  
1                 181  3.88  
2                  94  1.73  
3                   8  1.29  
4                 122  3.19

In [10]:
dummy = pd.get_dummies(data[["Gender","Extra_Curricular"]]).astype(int)

In [11]:
dummy.head()

Gender_Female  Gender_Male  Extra_Curricular_No  \
0              0            1                    0   
1              1            0                    0   
2              0            1                    0   
3              1            0                    1   
4              0            1                    1   

   Extra_Curricular_Societies  Extra_Curricular_Sports  
0                           1                        0  
1                           1                        0  
2                           1                        0  
3                           0                        0  
4                           0                        0

In [12]:
dummy.drop(["Gender_Female","Extra_Curricular_No"] , axis = 1 , inplace = True)

In [13]:
dummy.head()

Gender_Male  Extra_Curricular_Societies  Extra_Curricular_Sports
0            1                           1                        0
1            0                           1                        0
2            1                           1                        0
3            0                           0                        0
4            1                           0                        0

In [14]:
data.drop(["Gender","Extra_Curricular"], axis=1 , inplace = True)

In [15]:
data.head()

ID  Age  Study_Hours  Annual_Income  Distance_From_Home   GPA
0  8867   22           10        1318792                 154  1.76
1  1316   24            9         874657                 181  3.88
2  9443   22           15        1098331                  94  1.73
3  1829   25            9        1680585                   8  1.29
4  1989   26            7        1361560                 122  3.19

In [16]:
data.drop(["ID"],axis=1 , inplace=True)

In [17]:
data.head()

Age  Study_Hours  Annual_Income  Distance_From_Home   GPA
0   22           10        1318792                 154  1.76
1   24            9         874657                 181  3.88
2   22           15        1098331                  94  1.73
3   25            9        1680585                   8  1.29
4   26            7        1361560                 122  3.19

In [18]:
data_new = pd.concat([dummy,data], axis=1)

In [19]:
data_new.head()

Gender_Male  Extra_Curricular_Societies  Extra_Curricular_Sports  Age  \
0            1                           1                        0   22   
1            0                           1                        0   24   
2            1                           1                        0   22   
3            0                           0                        0   25   
4            1                           0                        0   26   

   Study_Hours  Annual_Income  Distance_From_Home   GPA  
0           10        1318792                 154  1.76  
1            9         874657                 181  3.88  
2           15        1098331                  94  1.73  
3            9        1680585                   8  1.29  
4            7        1361560                 122  3.19

In [20]:
x=data_new.iloc [:,:7].values

In [35]:
x

array([[      1,       1,       0, ...,      10, 1318792,     154],
       [      0,       1,       0, ...,       9,  874657,     181],
       [      1,       1,       0, ...,      15, 1098331,      94],
       ...,
       [      1,       0,       1, ...,       6, 1912975,      67],
       [      1,       1,       0, ...,      12,  341543,      86],
       [      1,       0,       0, ...,      12,  975142,      87]],
      dtype=int64)

In [21]:
y=data_new.iloc [:,7].values

In [22]:
y

array([1.76, 3.88, 1.73, 1.29, 3.19, 2.42, 3.05, 2.14, 2.07, 1.85, 2.8 ,
       3.09, 3.01, 3.25, 2.12, 1.87, 2.03, 1.59, 3.74, 1.31, 1.04, 3.45,
       2.77, 3.39, 3.87, 2.6 , 1.85, 3.65, 1.66, 1.47, 3.28, 3.16, 3.59,
       3.1 , 1.7 , 3.01, 3.58, 3.96, 1.45, 2.7 , 1.83, 1.03, 3.26, 2.11,
       3.26, 1.33, 3.07, 1.72, 1.49, 2.61, 3.49, 1.68, 2.93, 2.9 , 3.86,
       1.03, 1.84, 3.73, 3.92, 3.35, 2.65, 2.73, 3.95, 2.73, 1.56, 2.24,
       1.75, 2.38, 2.68, 3.49, 2.  , 3.14, 1.88, 2.02, 3.79, 1.05, 1.55,
       1.42, 3.88, 3.51, 2.58, 1.78, 2.43, 3.52, 1.34, 3.43, 2.61, 2.86,
       1.63, 3.16, 3.98, 3.41, 1.86, 1.11, 2.88, 2.58, 2.62, 1.5 , 3.09,
       1.58, 1.4 , 3.39, 1.16, 1.1 , 3.61, 3.26, 3.22, 1.94, 3.88, 3.08,
       3.17, 3.7 , 3.47, 2.42, 3.85, 3.53, 3.41, 2.76, 3.07, 3.5 , 1.52,
       3.63, 2.67, 3.39, 3.2 , 3.87, 3.02, 1.87, 1.77, 3.61, 1.38, 3.7 ,
       3.27, 1.97, 2.43, 3.16, 2.65, 1.82, 3.24, 1.56, 2.18, 1.55, 3.61,
       3.96, 1.82, 2.91, 2.3 , 3.72, 3.86, 1.7 , 2.

In [31]:
x_train,x_test ,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [32]:
model= LinearRegression()

In [33]:
model.fit(x_train,y_train)

LinearRegression()

In [48]:
y_test

array([2.37, 2.5 , 1.08, 2.25, 3.46, 3.75, 3.65, 3.81, 3.38, 1.21, 2.57,
       1.42, 1.62, 2.78, 3.88, 1.03, 3.48, 1.6 , 2.12, 1.42, 3.16, 3.84,
       2.09, 2.4 , 2.03, 3.73, 1.33, 1.1 , 1.47, 3.88, 3.23, 1.96, 1.11,
       1.68, 1.37, 3.37, 1.49, 1.01, 3.56, 1.61, 1.79, 2.7 , 3.11, 3.44,
       1.95, 2.47, 2.86, 1.55, 1.54, 2.26, 1.38, 2.53, 3.83, 1.29, 3.54,
       3.94, 1.13, 1.2 , 2.19, 2.72, 1.85, 2.36, 3.61, 1.96, 1.42, 3.43,
       1.41, 3.1 , 1.47, 2.84, 3.08, 2.35, 1.06, 3.07, 3.46, 3.29, 2.07,
       3.15, 2.41, 1.62, 3.22, 3.99, 3.17, 3.3 , 1.2 , 1.34, 1.97, 3.45,
       1.25, 1.27, 2.3 , 3.4 , 2.3 , 2.22, 1.93, 1.4 , 3.71, 3.88, 1.47,
       1.23, 2.64, 1.57, 2.24, 2.23, 2.86, 3.5 , 2.84, 1.24, 2.35, 2.44,
       1.5 , 2.43, 2.58, 1.55, 3.21, 1.09, 3.37, 3.69, 2.49, 3.12, 3.38,
       2.1 , 2.67, 1.34, 2.65, 2.52, 1.87, 2.89, 1.99, 3.59, 2.28, 1.13,
       3.34, 1.77, 2.08, 1.21, 2.85, 2.07, 2.11, 3.01, 3.39, 3.75, 1.58,
       3.46, 2.64, 3.31, 2.82, 1.84, 3.86, 1.7 , 3.

In [41]:
y_pred = model.predict(x_test)
y_pred

array([2.45859544, 2.48189844, 2.52609814, 2.44755148, 2.43441844,
       2.4441942 , 2.59304194, 2.5650934 , 2.45743111, 2.54705058,
       2.41369892, 2.48703529, 2.54110891, 2.55756711, 2.40964999,
       2.6464932 , 2.55155379, 2.49226051, 2.61246241, 2.58476053,
       2.48632814, 2.62401499, 2.40425402, 2.54747027, 2.52877333,
       2.53210703, 2.58689872, 2.42520324, 2.5997469 , 2.51215648,
       2.55717346, 2.57209611, 2.41712661, 2.51984043, 2.48485112,
       2.53237746, 2.47437727, 2.52478684, 2.62616758, 2.53023872,
       2.60300406, 2.46409328, 2.44288531, 2.52653268, 2.54175963,
       2.43226457, 2.38444236, 2.54421868, 2.39457219, 2.45051988,
       2.45748266, 2.54048337, 2.39321516, 2.45221297, 2.54202793,
       2.60474351, 2.37836383, 2.60193504, 2.64836809, 2.47970387,
       2.60829197, 2.43343052, 2.46820314, 2.43089338, 2.48106334,
       2.54937679, 2.5677143 , 2.50048765, 2.50381686, 2.59987949,
       2.54103206, 2.5374847 , 2.54089681, 2.41464698, 2.54079

In [43]:
MSE =mean_squared_error(y_pred, y_test)
MSE

0.7423989909750032

In [46]:
RMSE = np.sqrt(MSE)

In [47]:
RMSE

0.8616257836062029

In [49]:
data_new.head()

Gender_Male  Extra_Curricular_Societies  Extra_Curricular_Sports  Age  \
0            1                           1                        0   22   
1            0                           1                        0   24   
2            1                           1                        0   22   
3            0                           0                        0   25   
4            1                           0                        0   26   

   Study_Hours  Annual_Income  Distance_From_Home   GPA  
0           10        1318792                 154  1.76  
1            9         874657                 181  3.88  
2           15        1098331                  94  1.73  
3            9        1680585                   8  1.29  
4            7        1361560                 122  3.19

In [50]:
x.shape

(1000, 7)

In [65]:
arr =np.array([1,1,0,18,18,1318792,9]).reshape(1,7)

In [66]:
model.predict(arr)

array([2.3811854])

In [70]:
arr2 =np.array([0,0,0,19,2,574657,154]).reshape(1,7)

In [71]:
model.predict(arr2)

array([2.47891401])